apiVersion: v1
kind: Service
metadata:
  labels:
    svc: dummy-sv
  namespace: dummy-ns
  name: dummy-svc
spec:
  type: NodePort
  ports:
  - nodePort: 31313
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    svc: controller
  sessionAffinity: None
