apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: dummy-ns
  name: logger
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      svc: logger
  template:
    metadata:
      labels:
        svc: logger
    spec:
      containers:
      - name: logger
        image: alpine:3.6
        imagePullPolicy: IfNotPresent
        command:
        - "sleep"
        args:
        - "3600"
  updateStrategy:
    type: OnDelete
