apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    example: deployment
  namespace: dummy-ns
  name: example-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      svc: controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        svc: controller
    spec:
      containers:
      - name: controller
        command:
        - "sleep"
        args:
        - "3600"
        image: alpine:3.6
        imagePullPolicy: IfNotPresent
