# kubectl run php-apache --image=k8s.gcr.io/hpa-example --requests=cpu=200m --expose --port=80
# kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10
# kubectl run -i --tty load-generator --image=busybox /bin/sh
#  > while true; do wget -q -O- http://php-apache.default.svc.cluster.local; done
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-apache
  targetCPUUtilizationPercentage: 50
